# 標準入力

In [ ]:
A, B = map(int, input().split())
A = list(map(int, input().split()))


# 文字列の中の特定の文字のインデックスを探す

In [1]:
S =  "RNBQKBNR"
# 前から探す
f_i = S.find("R")
# 後ろから探す
l_i = S.rfind("R")

# 二つの数字の偶奇が異なる

それぞれの数字を2で割った余りは異なれば、偶奇が異なる

位置の偶奇が異なるとは、間に挟まっている文字が偶数個である

In [5]:
#偶奇が異なる
print(1 % 2 == 2 % 2)

#同じ
print(4%2==2%2)

False
True


# 複数のif条件
if分を変数で定義して、print内にandで条件付けする

In [6]:
S = input()
c1 = (S.rfind('B') - S.find('B')) % 2 == 1
c2 = S.find('R') < S.find('K') < S.rfind('R')
print('Yes' if c1 and c2 else 'No')

No


# 文字列の特定の文字を、違う文字に変える

replace()関数を用いる

In [1]:
H = int(input())
for _ in range(H):
    print(input().replace('TT', 'PC'))

PCg
1PC


# 変数を大きさによって、入れ替える

In [1]:
def swap(a, b):
    if (b > a):
        a, b = b, a
    return a, b

# リストの縦方向の要素の総和

In [2]:
A = [[1,2,3],[3,4,5]]
W = 3
H = 2

Col = [0] * (W)

for i in range(W):
    for j in range(H):
        Col[i] += A[j][i]

# dict内のlistを競プロ用に出力をする

In [5]:
ans = {0: [1, 2, 3], 1: [4, 5, 6], 2: [7, 8, 9]}
for i in range(3):
    print(" ".join(map(str, ans[i])))

1 2 3
4 5 6
7 8 9


# 組み合わせを列挙(全探索)

In [7]:
from itertools import combinations
A = [1,2,3]
r = 2
combination = list(combinations(A,r))
print(combination)

[(1, 2), (1, 3), (2, 3)]


# 桁数を指定して、十進数を二進数にする

In [10]:
N = 3 #3桁に指定
x = 5 #5を2進数表記にする
print(format(x, "0"+str(N)+"b"))

101


# 指定した文字の組み合わせとなる文字を作る

In [4]:
from itertools import product

N = 2
for S in product(['(', ')'], repeat=N):
    print(S)

('(', '(')
('(', ')')
(')', '(')
(')', ')')


# リスト内の同じ値をもつ要素のインデックスを取得

In [9]:
mylist = [1, 2, 3, 4, 5, 3, 3,]
indexes = [i for i, e in enumerate(mylist) if e == 3]
print(indexes)

[2, 5, 6]


# 行列の回転

4回回転して元通りになるということは、(+-)90度回転を表す

In [1]:
import numpy as np

#90度に回転
a = [[1,2,3], [4,5,6],[7,8,9]]
a = np.rot90(a)
a = np.rot90(a)
print(np.rot90(a))

print("-"*10)
'''
-90度に回転
N = len(A)
A[i][j] => A[N+1-j][i]方向に回転

下の例では、N=3
'''
a = [[1,2,3], [4,5,6],[7,8,9]]

'''
以下の場合には、うまくいかない
対策：
https://teratail.com/questions/gqpyjznf4d82t0
preA = a
'''
preA = [[1,2,3], [4,5,6],[7,8,9]]
N = len(a)
for i in range(N):
    for j in range(N):
        a[N-i-1][j] = preA[j][i]
print(a)

[[7 4 1]
 [8 5 2]
 [9 6 3]]
----------
[[3, 6, 9], [2, 5, 8], [1, 4, 7]]


# 行列の中の値が、他の行列の値に含まれるか確認

In [24]:
import numpy as np

'''
aの行列にある1が、bの行列にある1の場所にもあるか確認
'''
a = np.array([[0, 1, 1], [1, 1, 1], [1, 0 , 1]])
b = np.array([[0, 1, 1], [1, 1, 1,], [1, 1, 1]])
print(np.min(b-a) >= 0)



'''
文字列の場合
'''
a = [["t", "t", "k"], ["k", "t", "k"], ["t", "t", "k"]]
b = [["t", "k", "k"], ["k", "k", "k"], ["t", "t", "k"]]

def convert(matlix):
    for i in range(len(matlix)):
        for j in range(len(matlix[i])):
            if matlix[i][j] == "t":
                matlix[i][j] = 1
            else:
                matlix[i][j] = 0
    return matlix
a = np.array(convert(a))
b = np.array(convert(b))
print(np.min(b-a) >0 )

True
False
